---
resources:
  cloud: aws  # The cloud to use (optional).

  # The region to use (optional). Auto-failover will be disabled
  # if this is specified.
  region: eu-west-2

  instance_type: r6g.xlarge

file_mounts:
  ~/.qdrant_bge-base-en: s3://discovery-generative-ai/indexes/nesta_way/qdrant_bge-base-en

setup: |
  conda activate slackbot
  if [ $? -ne 0 ]; then
    conda create -n slackbot python=3.9 poetry -y
    conda deactivate
    conda activate slackbot
  fi

  poetry --version || echo "Check if poetry is installed!"

  git clone -b 49-slack-bot git@github.com:nestauk/discovery_generative_ai.git || true

  cd discovery_generative_ai
  make init

  echo 'Setting up nginx with public ipv4 at...'
  export ADDRESS=`ec2metadata --public-ipv4`
  echo $ADDRESS

  sudo apt-get update -y && sudo apt install nginx -y
  cd /etc/nginx/sites-enabled/
  echo \
  "server {
    listen 80;
    server_name $ADDRESS;
    location / {
      proxy_pass http://0.0.0.0:8000;
    }
  }
  " | sudo tee fastapi_nginx

run: |
  conda activate slackbot
  echo 'Starting nginx service...'
  sudo service nginx restart
  echo 'Starting slackbot app...'
  python -u -m genai.slackbot.serve_vdb 2>&1 | tee api_server.log &

  echo 'Waiting for slackbot to start...'
  while ! `cat api_server.log | grep -q 'Uvicorn running on'`; do sleep 1; done
  echo 'Slackbot started!'
