---
resources:
  cloud: aws  # The cloud to use (optional).

  # The region to use (optional). Auto-failover will be disabled
  # if this is specified.
  region: eu-west-2

  cpus: 4+
  memory: 4+

setup: |
  conda activate slackbot
  if [ $? -ne 0 ]; then
    conda create -n slackbot python==3.9.17 poetry -y
    conda deactivate
    conda activate slackbot
  fi

  poetry --version || echo "Check if poetry is installed!"

  git clone -b 49-slack-bot git@github.com:nestauk/discovery_generative_ai.git || true

  cd discovery_generative_ai
  make init

run: |
  conda deactivate
  conda activate slackbot
  echo 'Starting slackbot app...'
  cd ~/sky_workdir/discovery_generative_ai/src/slackbot
  TOKENIZERS_PARALLELISM=true python -u -m slackbot_socket 2>&1 | tee api_server.log &

  echo 'Waiting for slackbot to start...'
  while ! `cat api_server.log | grep -q 'Bolt app is running!'`; do sleep 1; done
  echo 'Slackbot started!'
