---
name: Status Checks

on:
  push:
    branches-ignore:
      - production
      - main

# Stops the currently running workflow if a new one has been triggered
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/poetry/setup
        with:
          python_version: "3.9.18"

      - name: Install Python Lint Dependencies with Poetry
        shell: bash
        run: poetry install --with lint

      - name: Lint
        uses: ./.github/actions/poetry/pre-commit-lint
